### ISSUE TITLE
Failed to download skin at start

### ISSUE THREAD

**Issue by Xardas88** [InventivetalentDev/Murder#18]
## What steps will reproduce the problem?  
1. when the server starts
2. the commands don't work 

## What were you expecting to happen? What happened instead?  
load the plugin Murder. Not load because on an error
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Murder 3.1.2
## What Spigot version are you using? *Type /version*  
Spigot 1.9 (1.9-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
ResourcePackApi, MenuBuilder, PacketListenerApi, ViaVersion, NickNamer, NPCLib, Murder
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/rgcFSd7y
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm testing the server standalone. if it works I'll try to put it to Bungeecord

**Comment by Xardas88** [comment]
up

i try to use all plugin dependencies update on last version and not but always generates this error

Error occurred while enabling Murder v3.1.2 (Is it up to date?)
java.lang.RuntimeException: Failed to load skin data
	at org.inventivetalent.murder.skin.SkinManager.<init>(SkinManager.java:57) ~[?:?]
	at org.inventivetalent.murder.Murder.onEnable(Murder.java:223) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.RuntimeException: Failed to download skin '1'. Received String: ''
	at org.inventivetalent.murder.skin.SkinManager.load(SkinManager.java:118) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.loadLocal(SkinManager.java:87) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.load(SkinManager.java:79) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.<init>(SkinManager.java:55) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://api.inventivetalent.org/skin/murder/?s=1
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_121]
	at org.inventivetalent.murder.skin.SkinManager$1.getInput(SkinManager.java:105) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager$1.getInput(SkinManager.java:102) ~[?:?]
	at com.google.common.io.CharStreams$3.openStream(CharStreams.java:556) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at com.google.common.io.CharSource.read(CharSource.java:162) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at com.google.common.io.CharStreams.toString(CharStreams.java:216) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
	at org.inventivetalent.murder.skin.SkinManager.load(SkinManager.java:102) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.loadLocal(SkinManager.java:87) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.load(SkinManager.java:79) ~[?:?]
	at org.inventivetalent.murder.skin.SkinManager.<init>(SkinManager.java:55) ~[?:?]
	... 12 more

there seems to be a problem with the skins download

pls i need for my server
