### ISSUE TITLE
Plugin not working on 1.10.2

### ISSUE THREAD

**Issue by ZakkProjects** [InventivetalentDev/Murder#31]
## What steps will reproduce the problem?  
1. install the plugin 
2. typed /murder to chat
3. but the command don´t exists

## What were you expecting to happen? What happened instead?  
- instead of the normal work of my jumps commands that do not exist
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
- 3.3.1 - Snapshot
## What Spigot version are you using? *Type /version*  
- 1.10.2 git-spigot
## What plugins are you using? *Type /plugins*  
- https://ctrlv.cz/nv4N
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
- server log : 
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
- No any crash
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
- I installed this game first time

**Comment by ZakkProjects** [comment]
sorry https://pastebin.com/AmSUFNw2 at the end of file line 1220

**Comment by InventivetalentDev** [comment]
Did you reload your server? If you did, please fully restart it.

**Comment by ZakkProjects** [comment]
I´ve restarted server and full VPS server. But none.

**Comment by techboy04** [comment]
The same thing has happened to me, but I just added everything in a private
server with no mods and it seems to work alittle bit better (There is a few
errors but I will post a ticket on that)

**Comment by ZakkProjects** [comment]
It is possible that the error in any of the plugins? Since Java little confess I checked it, but no plugin does not use the same classes, and functions.

**Comment by ZakkProjects** [comment]
expect a global function Minecraft

**Comment by ZakkProjects** [comment]
Out of boredom, I went through the entire log and found the following ( https://pastebin.com/AmSUFNw2 ) :
error in PacketlistenerAPI ---- line 73
error in NPClib --------- line 120
error in NPClib(2) -------line 208
error in Murder ---------line 1224 [Registry for 'Murder' already exists]
Thats all errors with inventivetalent class.

**Comment by techboy04** [comment]
For me, everything was updated even I checked Java and it was fine.

**Comment by techboy04** [comment]
But I still had problems (I will post an Issue on it)

**Comment by MagicSecret** [comment]
Hey, the plugin will also not work for me

**Comment by MagicSecret** [comment]
This is my error: 

> > [21:12:49 ERROR]: Error occurred while disabling Murder v3.3.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
at org.inventivetalent.murder.Murder.saveData(Murder.java:240) ~[?:?]
at org.inventivetalent.murder.Murder.onDisable(Murder.java:224) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [server.jar:git-Spigot-72c2605-251a5b6]
at org.inventivetalent.murder.Murder.onEnable(Murder.java:160) [Murder_v3.3.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [server.jar:git-Spigot-72c2605-251a5b6]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [server.jar:git-Spigot-72c2605-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [server.jar:git-Spigot-72c2605-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [server.jar:git-Spigot-72c2605-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [server.jar:git-Spigot-72c2605-251a5b6]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [server.jar:git-Spigot-72c2605-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [server.jar:git-Spigot-72c2605-251a5b6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
